package com.javaclimb.xshopping.mapper;

import com.javaclimb.xshopping.entity.OrderGoodsRela;
import org.springframework.stereotype.Repository;

@Repository
public interface OrderGoodsRelaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_rela
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_rela
     *
     * @mbg.generated
     */
    int insert(OrderGoodsRela row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_rela
     *
     * @mbg.generated
     */
    int insertSelective(OrderGoodsRela row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_rela
     *
     * @mbg.generated
     */
    OrderGoodsRela selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_rela
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderGoodsRela row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods_rela
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderGoodsRela row);
}