package com.javaclimb.xshopping.mapper;

import com.javaclimb.xshopping.entity.UserInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import tk.mybatis.mapper.common.Mapper;

import java.util.List;

@Repository
public interface UserInfoMapper extends Mapper<UserInfo> {
    List<UserInfo> findByName(@Param("name") String name);



    /*增删改查的方法全部省略，使用tk.mapper中的语句即可*/

    /*
    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     *//*
    int deleteByPrimaryKey(Long id);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     *//*
    int insert(UserInfo row);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     *//*
    int insertSelective(UserInfo row);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     *//*
    UserInfo selectByPrimaryKey(Long id);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     *//*
    int updateByPrimaryKeySelective(UserInfo row);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     *//*
    int updateByPrimaryKey(UserInfo row);*/
}