package com.javaclimb.xshopping.entity;

/**
 * Database Table Remarks:
 *   订单商品关系映射表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_goods_rela
 */
public class OrderGoodsRela {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_rela.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   所属订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_rela.orderId
     *
     * @mbg.generated
     */
    private Long orderid;

    /**
     * Database Column Remarks:
     *   所属商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_rela.goodsId
     *
     * @mbg.generated
     */
    private Long goodsid;

    /**
     * Database Column Remarks:
     *   商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods_rela.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_rela.id
     *
     * @return the value of order_goods_rela.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_rela.id
     *
     * @param id the value for order_goods_rela.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_rela.orderId
     *
     * @return the value of order_goods_rela.orderId
     *
     * @mbg.generated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_rela.orderId
     *
     * @param orderid the value for order_goods_rela.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_rela.goodsId
     *
     * @return the value of order_goods_rela.goodsId
     *
     * @mbg.generated
     */
    public Long getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_rela.goodsId
     *
     * @param goodsid the value for order_goods_rela.goodsId
     *
     * @mbg.generated
     */
    public void setGoodsid(Long goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods_rela.count
     *
     * @return the value of order_goods_rela.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods_rela.count
     *
     * @param count the value for order_goods_rela.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}